### ISSUE TITLE
Add alternate answers

### ISSUE THREAD

**Issue by jimgerth** [jimgerth/sayilar-flutter#16]
Sometimes it might be nice to not have one specific answer that the user must put in exactly, but rather have a few alternate answers that are also correct.
For example for translating _100_, _yüz_ _("hundred")_ is sufficient and preferred, but _bir yüz_ _("one hundred")_ really isn't incorrect either.
(Or thinking about telling time for #15, the leading _saat_ is always optional, so alternate answers would be nice there as well.)

Also it might be nice to split the answer strings at whitespace and compare the results, so that accidentally adding two spaces between words in the answer does not make it incorrect.

**Comment by JimGerth** [comment]
#23 makes grading more robust by ignoring whitespace between words, as suggested in this issue.
It also adds support for alternate answers.
However no specific alternate answers are actually given yet, so I'll leave this issue open.

**Comment by jimgerth** [comment]
As mentioned, alternate answers are already supported and the time related questions introduced in #24 already make extensive use of them.

Thus I‘ll close this issue.

When concrete requests for other alternate answers arise, new issues can be opened for them.
